CATEGORIES = (
    ("LIT", "Literature"),
    ("THR", "Thriller"),
    ("COK", "Cookbook"),
    ("KID", "Children"),
    ("BIO", "Biography"),
)
FOTO_URLS = [
    "https://media.s-bol.com/QknoJzrlnZn9/550x661.jpg",
    "https://media.s-bol.com/YE6DZEZ6ro4W/550x765.jpg",
    "https://media.s-bol.com/gZo60krq64xl/546x840.jpg",
    "https://media.s-bol.com/48ZkKkpAQw5x/550x784.jpg",
    "https://media.s-bol.com/736pmNNEJBXO/550x761.jpg",
    "https://media.s-bol.com/nxoro0qr2rGW/550x440.jpg",
    "https://media.s-bol.com/Y6gPY6DZOlAW/550x780.jpg",
    "https://media.s-bol.com/oNOonokWgAA/544x840.jpg",
    "https://media.s-bol.com/311jppqJ5MXO/550x790.jpg",
    "https://media.s-bol.com/R6OjQ6V6YjGE/550x701.jpg",
    "https://media.s-bol.com/L8Bl26Xyy8WX/550x461.jpg",
    "https://media.s-bol.com/R2Mqrv04kEY/550x709.jpg",
    "https://media.s-bol.com/R27YMg1XVKY/537x840.jpg",
    "https://media.s-bol.com/qxY1Go0ZoP8D/550x717.jpg",
    "https://media.s-bol.com/q7L90BL1Jz3p/545x840.jpg",
    "https://media.s-bol.com/vo5XZXY5D9An/550x550.jpg",
]
TITLES = [
    "When the Bough Breaks",
    "They All Lie",
    "Men in White",
    "Girl in the Park, The",
    "Glass-blower's Children, The (Glasblåsarns barn)",
    "Wake of the Red Witch",
    "Oversimplification of Her Beauty, An",
    "Pride and Glory",
    "Goddess, The",
    "Story of Yonosuke, A (Yokomichi Yonosuke)",
    "Desperados, The",
    "Shane",
    "Nightcrawler",
    "Brides of Dracula",
    "Kill Switch",
    "Nobody Else But You (Poupoupidou)",
    "Souper, Le (Supper, The)",
    "Lapland Odyssey (Napapiirin sankarit)",
    "Patterns",
    "One Nine Nine Four",
    "Night Porter, The (Portiere di notte, Il)",
    "Murder in Coweta County",
    "Killing of America, The",
    "Sentimental Swordsman, The (To ching chien ko wu ching chien)",
    "Tattoo",
    "Fatty Drives the Bus",
    "Swinger, The",
    "247°F ",
    "How Bruce Lee Changed the World",
    "Cold Comes the Night",
    "Day of the Dead",
    "Imagine",
    "Highway to Hell",
    "Housekeeper, The (femme de ménage, Une)",
    "Crank",
    "Wavelength",
    "Twilight of the Golds, The",
    "Big Trees, The",
    "...tick... tick... tick...",
    "Curse of Chucky (Child's Play 6)",
    "Broderskab (Brotherhood)",
    "Howard the Duck",
    "St. George Shoots the Dragon (Sveti Georgije ubiva azdahu)",
    "American Horror House (Sorority Horror House)",
    "Heirloom, The (Zhai Ban)",
    "Soul Plane",
    "Rollo and the Woods Sprite (Rölli ja metsänhenki)",
    "White Noise 2: The Light",
    "Farscape: The Peacekeeper Wars",
    "Hollow Man",
    "Yes Men Fix the World, The",
    "Mary Poppins",
    "Ten Skies",
    "Terminal, The",
    "Coupe de Ville",
    "Skins",
    "Kings of Mykonos, The",
    "'71",
    "Making of a Legend: Gone with the Wind, The",
    "Baggage Claim",
    "Forty-first, The (Sorok pervyy)",
    "From Beyond",
    "Handmaid's Tale, The",
    "Warriors of Heaven and Earth (Tian di ying xiong)",
    "Hesher",
    "Frankenstein Must Be Destroyed",
    "Yankee Doodle Dandy",
    "Unreal Dream: The Michael Morton Story, An",
    "I Am Fishead",
    "Aurora Borealis",
    "You Will Be My Son (Tu seras mon fils)",
    "Wedding Singer, The",
    "Clownhouse",
    "Air Crew",
    "Nobel Son",
    "All-Star Superman",
    "Traces of Red",
    "Black Room, The",
    "Milius",
    "Black Room, The",
    "End of Suburbia: Oil Depletion and the Collapse of the American Dream",
    "Crave",
    "River of Grass",
    "Violet & Daisy",
    "Super Duper Alice Cooper",
    "Forbidden",
    "Sweet Bunch (Glykia symmoria)",
    "Main Street",
    "My Wife's Relations",
    "Did You Hear About the Morgans?",
    "Tomorrow at Dawn (Demain dès l'aube)",
    "Talcum Powder",
    "Sadie Thompson",
    "Woman Rebels, A (Portrait of a Rebel)",
    "El chocolate del loro",
    "Interview, The",
    "So Fine",
    "Demonic",
    "We Steal Secrets: The Story of WikiLeaks",
    "Blackbeard, the Pirate",
]
